// 50 Kategori Pengeluaran (Expenses) Default
export const EXPENSE_CATEGORIES = [
  "Gaji Karyawan",
  "Sewa Tempat / Gedung",
  "Listrik",
  "Air",
  "Internet & Telepon",
  "Bahan Baku Utama",
  "Bahan Penolong",
  "Kemasan / Packaging",
  "Biaya Pengiriman / Ongkir",
  "Pemasaran & Iklan (Ads)",
  "Pemeliharaan Alat / Mesin",
  "Perbaikan Gedung",
  "Asuransi Bisnis",
  "Pajak Usaha",
  "Biaya Legal & Notaris",
  "Biaya Perizinan",
  "ATK (Alat Tulis Kantor)",
  "Biaya Konsumsi / Dapur Kantor",
  "Bensin / Transportasi",
  "Parkir & Tol",
  "Biaya Tolak / Retur Produk",
  "Susut Nilai (Depresiasi Aset)",
  "Hosting & Domain (IT)",
  "Software Langganan (SaaS)",
  "Komisi Afiliasi / Sales",
  "Biaya Influencer / KOL",
  "Cetak Brosur / Banner",
  "Pelatihan / Training Karyawan",
  "Biaya Seragam Karyawan",
  "THR & Bonus Karyawan",
  "BPJS Ketenagakerjaan",
  "BPJS Kesehatan",
  "Biaya Kebersihan / Sampah",
  "Keamanan / Satpam",
  "Biaya Bank & Administrasi",
  "Potongan Payment Gateway / Pajak App",
  "Bunga Pinjaman Bank",
  "Denda Keterlambatan",
  "Biaya Konsultan",
  "Biaya Audit Keuangan",
  "Fotografi / Videografi Produk",
  "Pengadaan Barang Promo / Giveaway",
  "Biaya CSR / Sumbangan",
  "Iuran Warga / RT",
  "Biaya Rapat / Meeting",
  "Perjalanan Dinas",
  "Biaya Entertainment / Menjamu Klien",
  "Kerusakan Barang (Spoilage)",
  "Kehilangan Barang",
  "Lain-lain (Tak Terduga)"
];

// 25 Kategori Pemasukan (Incomes) Default
export const INCOME_CATEGORIES = [
  "Penjualan Produk Utama",
  "Penjualan Produk Sampingan",
  "Pendapatan Jasa / Layanan",
  "Pendapatan Subskripsi / Langganan",
  "Ongkos Kirim Dibayar Pelanggan",
  "Komisi / Afiliasi",
  "Royalti",
  "Pendapatan Franchise",
  "Penjualan Aset Bekas",
  "Pendapatan Bunga Bank",
  "Return on Investment (ROI)",
  "Diskon dari Supplier / Rabat",
  "Cashback Payment Gateway",
  "Pendapatan Iklan / Sponsor",
  "Uang Muka / DP Pelanggan",
  "Denda Keterlambatan Pelanggan",
  "Pendapatan Event / Bazaar",
  "Penjualan Barang Konsinyasi",
  "Penyewaan Alat / Ruang",
  "Hibah / Sumbangan / Investor",
  "Pendapatan Pelatihan / Workshop",
  "Pendapatan Merchandise",
  "Keuntungan Selisih Kurs",
  "Pendapatan Lisensi",
  "Pendapatan Lain-lain"
];
