import { sendWhatsAppWebhook } from './whatsapp';

export interface WhatsAppReportData {
  businessName: string;
  reportType: 'cashflow' | 'projection' | 'simulation' | 'summary';
  data: any;
}

export const whatsappReportService = {
  // Send cashflow report via WhatsApp
  async sendCashflowReport(data: WhatsAppReportData, phoneNumber?: string) {
    const { businessName, reportType, data: reportData } = data;
    
    const message = `
📊 *Laporan Cashflow - ${businessName}*

*Total Pemasukan:* Rp ${this.formatCurrency(reportData.totalIncome)}
*Total Pengeluaran:* Rp ${this.formatCurrency(reportData.totalExpense)}
*Saldo Akhir:* Rp ${this.formatCurrency(reportData.balance)}
*Jumlah Transaksi:* ${reportData.transactionCount}

_Generated by ProjeksiSaaS_
    `.trim();

    return await sendWhatsAppWebhook(message, phoneNumber);
  },

  // Send projection report via WhatsApp
  async sendProjectionReport(data: WhatsAppReportData, phoneNumber?: string) {
    const { businessName, reportType, data: reportData } = data;
    
    const message = `
📈 *Laporan Proyeksi - ${businessName}*

*BEP:* ${reportData.bep.toFixed(2)} unit
*ROI:* ${reportData.roi.toFixed(2)}%
*Profit Bulanan:* Rp ${this.formatCurrency(reportData.profit)}
*Profit Tahunan:* Rp ${this.formatCurrency(reportData.summary.annual_profit)}

_Generated by ProjeksiSaaS_
    `.trim();

    return await sendWhatsAppWebhook(message, phoneNumber);
  },

  // Send simulation report via WhatsApp
  async sendSimulationReport(data: WhatsAppReportData, phoneNumber?: string) {
    const { businessName, reportType, data: reportData } = data;
    
    const message = `
🎯 *Laporan Simulasi - ${businessName}*

*Skenario:* ${reportData.scenario}
*Profit Sebelum:* Rp ${this.formatCurrency(reportData.before.profit)}
*Profit Sesudah:* Rp ${this.formatCurrency(reportData.after.profit)}
*Perubahan Profit:* ${reportData.impact.profitChangePercent.toFixed(2)}%

_Generated by ProjeksiSaaS_
    `.trim();

    return await sendWhatsAppWebhook(message, phoneNumber);
  },

  // Send summary report via WhatsApp
  async sendSummaryReport(data: WhatsAppReportData, phoneNumber?: string) {
    const { businessName, reportType, data: reportData } = data;
    
    const message = `
📊 *Ringkasan Bisnis - ${businessName}*

*Total Pemasukan:* Rp ${this.formatCurrency(reportData.cashflow?.totalIncome || 0)}
*Total Pengeluaran:* Rp ${this.formatCurrency(reportData.cashflow?.totalExpense || 0)}
*Saldo Akhir:* Rp ${this.formatCurrency(reportData.cashflow?.balance || 0)}
*Jumlah Proyeksi:* ${reportData.projections?.length || 0}
*Jumlah Simulasi:* ${reportData.simulations?.length || 0}

_Generated by ProjeksiSaaS_
    `.trim();

    return await sendWhatsAppWebhook(message, phoneNumber);
  },

  // Format currency helper
  formatCurrency(amount: number): string {
    return new Intl.NumberFormat('id-ID').format(amount);
  },
};
